In [1]:
import numpy as np
import pandas as pd

In [2]:
# Load Data From CSV
raw_data = pd.read_csv('datasets/kddcup.data_10_percent.gz', header=None)

In [3]:
labels= raw_data.iloc[:,raw_data.shape[1]-1:]

In [4]:
label_backup = labels

In [5]:
# Conditions start to be in categories
DOS = (labels[41] == 'back.') | (labels[41] == 'land.') | (labels[41] == 'neptune.') | (labels[41] == 'pod.') | (labels[41] == 'smurf.') | (labels[41] == 'teardrop.')
U2R = (labels[41] == 'buffer_overflow.') | (labels[41] == 'loadmodule.') | (labels[41] == 'perl.') | (labels[41] == 'rootkit.')
R2L = (labels[41] == 'ftp_write.') | (labels[41] == 'guess_passwd.') | (labels[41] == 'imap.') | (labels[41] == 'multihop.') | (labels[41] == 'phf.') | (labels[41] == 'spy.') | (labels[41] == 'warezclient.') | (labels[41] == 'warezmaster.')
probe = (labels[41] == 'satan.') | (labels[41] == 'ipsweep.') | (labels[41] == 'portsweep.') | (labels[41] == 'nmap.')
# Conditions end

labels['categories'] = np.where(DOS, 'dos', np.where(U2R, 'u2r', np.where(R2L, 'r2l', np.where(probe, 'probe', labels[41]))))

# This is just for testing purpose
# labels.loc[labels['categories'].isin(['u2r'])]

In [6]:
# labels = labels.loc[:,[41,'categories']]
labels

             41 categories
0       normal.    normal.
1       normal.    normal.
2       normal.    normal.
3       normal.    normal.
4       normal.    normal.
5       normal.    normal.
6       normal.    normal.
7       normal.    normal.
8       normal.    normal.
9       normal.    normal.
10      normal.    normal.
11      normal.    normal.
12      normal.    normal.
13      normal.    normal.
14      normal.    normal.
15      normal.    normal.
16      normal.    normal.
17      normal.    normal.
18      normal.    normal.
19      normal.    normal.
20      normal.    normal.
21      normal.    normal.
22      normal.    normal.
23      normal.    normal.
24      normal.    normal.
25      normal.    normal.
26      normal.    normal.
27      normal.    normal.
28      normal.    normal.
29      normal.    normal.
...         ...        ...
493991  normal.    normal.
493992  normal.    normal.
493993  normal.    normal.
493994  normal.    normal.
493995  normal.    normal.
493996  normal.    normal.
493997  normal.    normal.
493998  normal.    normal.
493999  normal.    normal.
494000  normal.    normal.
494001  normal.    normal.
494002  normal.    normal.
494003  normal.    normal.
494004  normal.    normal.
494005  normal.    normal.
494006  normal.    normal.
494007  normal.    normal.
494008  normal.    normal.
494009  normal.    normal.
494010  normal.    normal.
494011  normal.    normal.
494012  normal.    normal.
494013  normal.    normal.
494014  normal.    normal.
494015  normal.    normal.
494016  normal.    normal.
494017  normal.    normal.
494018  normal.    normal.
494019  normal.    normal.
494020  normal.    normal.

[494021 rows x 2 columns]

In [8]:
labels.loc[labels['categories'].isin(['u2r'])]

             41 categories
0       normal.    normal.
1       normal.    normal.
2       normal.    normal.
3       normal.    normal.
4       normal.    normal.
5       normal.    normal.
6       normal.    normal.
7       normal.    normal.
8       normal.    normal.
9       normal.    normal.
10      normal.    normal.
11      normal.    normal.
12      normal.    normal.
13      normal.    normal.
14      normal.    normal.
15      normal.    normal.
16      normal.    normal.
17      normal.    normal.
18      normal.    normal.
19      normal.    normal.
20      normal.    normal.
21      normal.    normal.
22      normal.    normal.
23      normal.    normal.
24      normal.    normal.
25      normal.    normal.
26      normal.    normal.
27      normal.    normal.
28      normal.    normal.
29      normal.    normal.
...         ...        ...
493991  normal.    normal.
493992  normal.    normal.
493993  normal.    normal.
493994  normal.    normal.
493995  normal.    normal.
493996  normal.    normal.
493997  normal.    normal.
493998  normal.    normal.
493999  normal.    normal.
494000  normal.    normal.
494001  normal.    normal.
494002  normal.    normal.
494003  normal.    normal.
494004  normal.    normal.
494005  normal.    normal.
494006  normal.    normal.
494007  normal.    normal.
494008  normal.    normal.
494009  normal.    normal.
494010  normal.    normal.
494011  normal.    normal.
494012  normal.    normal.
494013  normal.    normal.
494014  normal.    normal.
494015  normal.    normal.
494016  normal.    normal.
494017  normal.    normal.
494018  normal.    normal.
494019  normal.    normal.
494020  normal.    normal.

[494021 rows x 2 columns]